# Generated by Django 4.2.13 on 2024-07-10 15:48

from typing import Any

from django import VERSION
from django.db import migrations, models

# `CheckConstraint.check` was renamed to `condition` in Django 5.1. Pass the
# version-dependent keyword through a dict so neither name is type-checked
# against the stubs for the other version.
condition = models.Q(("priority__range", (-100, 100)))
constraint_kwargs: dict[str, Any] = (
    {"condition": condition} if VERSION >= (5, 1) else {"check": condition}
)
constraint = models.CheckConstraint(name="priority_range", **constraint_kwargs)


class Migration(migrations.Migration):
    dependencies = [
        ("django_tasks_database", "0004_dbtaskresult_started_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dbtaskresult",
            name="priority",
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="dbtaskresult",
            constraint=constraint,
        ),
    ]
